[package]
name = "4611hd/rg-jecs"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Planck = "yetanotherclown/planck@0.2.0-rc.2"
PlanckJabby = "yetanotherclown/planck-jabby@0.2.0-rc.1"
PlanckRunService = "yetanotherclown/planck-runservice@0.2.0-rc.1"
YetAnotherNet = "yetanotherclown/yetanothernet@0.10.0-alpha.5"
jabby = "alicesaidhi/jabby@0.2.0"
t = "osyrisrblx/t@3.1.1"
ui-labs = "pepeeltoro41/ui-labs@2.3.8"
tablekit = "ffrostflame/tablekit@0.2.2"
skilift = "alicesaidhi/skilift@0.3.1-rc.1"
