[package]
name = "4611hd/rg-jecs"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Planck = "yetanotherclown/planck@0.2.0-rc.1"
PlanckJabby = "yetanotherclown/planck-jabby@0.2.0-rc.1"
PlanckRunService = "yetanotherclown/planck-runservice@0.2.0-rc.1"
YetAnotherNet = "yetanotherclown/yetanothernet@0.10.0-alpha.5"
jabby = "alicesaidhi/jabby@0.2.0"
t = "osyrisrblx/t@3.1.1"
Lyra = "paradoxum-games/lyra@0.5.0-rc.0"
ui-labs = "pepeeltoro41/ui-labs@2.3.8"
